name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        uses: actions/checkout@v3
      - name: Build
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload My Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: gradle/artifacts/
      - name: Download My Artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: gradle/artifacts/