env:
  docker_username: pjanky
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  GIT_COMMIT: ${{ github.sha }}

name: hello-world
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        uses: actions/checkout@v3
      - name: Build
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload My Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: app/build/libs/
  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
      - name: Clone-down
        uses: actions/checkout@v3
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: app/build/libs/
      - name: Build Image
        run: ci/build-docker.sh
      - name: Push Image
        run: ci/push-docker.sh