env:
  docker_username: ${{ github.actor }}
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}

name: Java CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    steps:
    - name: Clone-down
      uses: actions/checkout@v3
    - name: Upload Repo Artifact
      uses: actions/upload-artifact@v3
      with:
        name: repo
        path: .
  Build:
    runs-on: ubuntu-latest
    needs: [Clone-down]
    container: gradle:6-jdk11
    steps:
      - name: Download Repo Artifact
        uses: actions/download-artifact@v3
        with:
          name: repo
          path: .
      - name: Build
        run: chmod +x ci/build-app.sh && ci/build-app.sh
      - name: Test
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh 
      - name: Upload My Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-executable
          path: app/build/libs/
  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
      - name: Download Repo Artifact
        uses: actions/download-artifact@v3
        with:
          name: repo
          path: .
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: my-executable
          path: app/build/libs/
      - name: Build Image
        run: ci/build-docker.sh
      - name: Push Image
        run: ci/push-docker.sh
  Component-test:
    runs-on: ubuntu-latest
    needs: [Docker-image]
    steps:
      - name: Download Repo Artifact
        uses: actions/download-artifact@v3
        with:
          name: repo
          path: .
      - name: Execute component test
        run: ci/component-test.sh
  Performane-test:
    runs-on: ubuntu-latest
    needs: [Docker-image]
    steps:
      - name: Download Repo Artifact
        uses: actions/download-artifact@v3
        with:
          name: repo
          path: .
      - name: Execute performance test
        run: ci/performance-test.sh